# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cqsequee6-mp-taco
  namespace: cqsequee6
spec:
  clusterName: cqsequee6
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cqsequee6
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: cqsequee6-mp-taco
        namespace: cqsequee6
      version: v1.22.5

